name: Build and Push Docker Image to GitHub Container Registry

on:
  push:
    tags:
      - 'v*.*.*'  # Matches tags like v0.1.0, v1.2.3, etc.

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}:${{ github.ref_name }} .

    - name: Push Docker image to GitHub Container Registry
      run: |
        docker push ghcr.io/${{ github.repository }}:${{ github.ref_name }}

